# House Prices Data Preprocessing

In [64]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as st
import seaborn as sns

#Libraries additionally added
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
import ast

#Regular Expressions
import re

# Study data files
hp_train_data_path = "../House_Prices_Data/house_prices_train.csv"
hp_test_data_path = "../House_Prices_Data/house_prices_test.csv"


# Read the House Prices Train & Test data 
hp_train_df = pd.read_csv(hp_train_data_path)
hp_test_df = pd.read_csv(hp_test_data_path)

In [65]:
#Display the House Prices Train DataFrame
hp_train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [66]:
#Display the House Prices Test  DataFrame
hp_test_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

## Data Preprocessing for Train Data

In [67]:
# Display basic information about the training dataset
print("Training Dataset Info:")
print(hp_train_df.info())

Training Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB
None

In [68]:
# Display basic statistics for numerical features in the training dataset
#print("\nTraining Dataset Statistics:")
#print(hp_train_df.describe())

In [69]:
# Display columns with missing values and their counts
missing_values = hp_train_df.isnull().sum()
missing_columns = missing_values[missing_values > 0]
print("Columns with Missing Values:")
print(missing_columns)

Columns with Missing Values:
LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

## Handle Null Values hp_train_df

In [70]:
# Handle missing values
# Dropping columns with a high percentage of missing values  >1000
## Only 'FireplaceQu' have 690

# columns = ['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature']
# hp_train_df.drop(columns=columns, inplace=True)

In [71]:
# Reveiw the columns after dropping 5 columns wiht high percentages of missing value
missing_values = hp_train_df.isnull().sum()
missing_columns = missing_values[missing_values > 0]
print("Columns with Missing Values:")
print(missing_columns)

Columns with Missing Values:
LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

## Impute Missing Values hp_train_df

    
    ## LotFrontage : Since the area of each street connected to the house property most likely have a similar area to other houses in its neighborhood , we can fill in missing values by the median LotFrontage of the neighborhood.

In [72]:
# Group by neighborhood and fill in missing value by the median LotFrontage of all the neighborhood
hp_train_df["LotFrontage"] = hp_train_df.groupby("Neighborhood")["LotFrontage"].transform(
    lambda x: x.fillna(x.median()))

# Alley : data description says NA means "no alley access"
hp_train_df["Alley"] = hp_train_df["Alley"].fillna("None")

# MasVnrArea and MasVnrType : NA most likely means no masonry veneer for these houses. 
# We can fill 0 for the area and None for the type.
hp_train_df["MasVnrType"] = hp_train_df["MasVnrType"].fillna("None")
hp_train_df["MasVnrArea"] = hp_train_df["MasVnrArea"].fillna(0)

# BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, and BsmtFinType2:
# For all these categorical basement-related features, NaN means that there is no basement.
for col in ('BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2'):
    hp_train_df[col] = hp_train_df[col].fillna('None')

# BsmtFinSF1, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, BsmtFullBath, and BsmtHalfBath: missing values are likely zero for having no basement
for col in ('BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath'):
    hp_train_df[col] = hp_train_df[col].fillna(0)

# Electrical : It has one NA value. Since this feature has mostly 'SBrkr', we can set that for the missing value.
hp_train_df['Electrical'] = hp_train_df['Electrical'].fillna(hp_train_df['Electrical'].mode()[0])

# FireplaceQu : data description says NA means "no fireplace"
hp_train_df["FireplaceQu"] = hp_train_df["FireplaceQu"].fillna("None")

# GarageType, GarageFinish, GarageQual, and GarageCond: Replacing missing data with None
for col in ('GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'):
    hp_train_df[col] = hp_train_df[col].fillna('None')

# GarageYrBlt, GarageArea, and GarageCars: Replacing missing data with 0 (Since No garage = no cars in such garage.)
for col in ('GarageYrBlt', 'GarageArea', 'GarageCars'):
    hp_train_df[col] = hp_train_df[col].fillna(0)

# PoolQC: data description says NA means "No Pool".
# That makes sense, given the huge ratio of missing value (+99%) and the majority of houses have no Pool at all in general.
hp_train_df["PoolQC"] = hp_train_df["PoolQC"].fillna("None")

# Fence: data description says NA means "no fence"
hp_train_df["Fence"] = hp_train_df["Fence"].fillna("None")

# MiscFeature: data description says NA means "no misc feature"
hp_train_df["MiscFeature"] = hp_train_df["MiscFeature"].fillna("None")

## If other columns shows missing values then apply

In [73]:
# # Impute missing values in numerical columns with the mean
# hp_train_df.fillna(hp_train_df.mean(), inplace=True)

# # Impute missing values in categorical columns with the mode
# hp_train_df.fillna(hp_train_df.mode().iloc[0], inplace=True)

# Review hp_train_df for missing values

In [75]:
# Reveiw the columns after:
# dropping columns wiht high percentages of missing value
# Fill null values with imputation strategy

missing_values = hp_train_df.isnull().sum()
missing_columns = missing_values[missing_values > 0]
print("Columns with Missing Values:")
print(missing_columns)

Columns with Missing Values:
Series([], dtype: int64)

## Check duplicates value for hp_train_df

In [76]:
# Check the number of unique values in each column
hp_train_df.nunique()

Id               1460
MSSubClass         15
MSZoning            5
LotFrontage       115
LotArea          1073
                 ...
MoSold             12
YrSold              5
SaleType            9
SaleCondition       6
SalePrice         663
Length: 81, dtype: int64

In [77]:
# Check for duplicated values in the 'Id' column
subset_columns = ['Id']
duplicate_rows_subset = hp_train_df[hp_train_df.duplicated(subset=subset_columns)]
if duplicate_rows_subset.empty:
    print("No duplicate rows based on 'Id' column.")
else:
    print("Duplicate rows based on 'Id' column:")
    print(duplicate_rows_subset)

No duplicate rows based on 'Id' column.

## Convert necessary columns to appropriate data types

In [78]:
# Convert 'LotFrontage' to int
hp_train_df['LotFrontage'] = hp_train_df['LotFrontage'].astype(int)

In [79]:
# Convert necessary columns to appropriate data types
hp_train_df['MSSubClass'] = hp_train_df['MSSubClass'].astype('category')
hp_train_df['MSZoning'] = hp_train_df['MSZoning'].astype('category')
hp_train_df['Street'] = hp_train_df['Street'].astype('category')
hp_train_df['LotShape'] = hp_train_df['LotShape'].astype('category')
hp_train_df['LandContour'] = hp_train_df['LandContour'].astype('category')

## Format Columns through Binning 

## Handle each necessary features using binning that have high category counts

In [80]:
hp_train_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [81]:
for column in hp_train_df.columns:
    unique_values = hp_train_df[column].unique()
    print(f" Unique values {column} count: {len(unique_values)}\n")

 Unique values Id count: 1460

 Unique values MSSubClass count: 15

 Unique values MSZoning count: 5

 Unique values LotFrontage count: 110

 Unique values LotArea count: 1073

 Unique values Street count: 2

 Unique values Alley count: 3

 Unique values LotShape count: 4

 Unique values LandContour count: 4

 Unique values Utilities count: 2

 Unique values LotConfig count: 5

 Unique values LandSlope count: 3

 Unique values Neighborhood count: 25

 Unique values Condition1 count: 9

 Unique values Condition2 count: 8

 Unique values BldgType count: 5

 Unique values HouseStyle count: 8

 Unique values OverallQual count: 10

 Unique values OverallCond count: 9

 Unique values YearBuilt count: 112

 Unique values YearRemodAdd count: 61

 Unique values RoofStyle count: 6

 Unique values RoofMatl count: 8

 Unique values Exterior1st count: 15

 Unique values Exterior2nd count: 16

 Unique values MasVnrType count: 4

 Unique values MasVnrArea count: 327

 Unique values ExterQual count: 4

 Unique values ExterCond count: 5

 Unique values Foundation count: 6

 Unique values BsmtQual count: 5

 Unique values BsmtCond count: 5

 Unique values BsmtExposure count: 5

 Unique values BsmtFinType1 count: 7

 Unique values BsmtFinSF1 count: 637

 Unique values BsmtFinType2 count: 7

 Unique values BsmtFinSF2 count: 144

 Unique values BsmtUnfSF count: 780

 Unique values TotalBsmtSF count: 721

 Unique values Heating count: 6

 Unique values HeatingQC count: 5

 Unique values CentralAir count: 2

 Unique values Electrical count: 5

 Unique values 1stFlrSF count: 753

 Unique values 2ndFlrSF count: 417

 Unique values LowQualFinSF count: 24

 Unique values GrLivArea count: 861

 Unique values BsmtFullBath count: 4

 Unique values BsmtHalfBath count: 3

 Unique values FullBath count: 4

 Unique values HalfBath count: 3

 Unique values BedroomAbvGr count: 8

 Unique values KitchenAbvGr count: 4

 Unique values KitchenQual count: 4

 Unique values TotRmsAbvGrd count: 12

 Unique values Functional count: 7

 Unique values Fireplaces count: 4

 Unique values FireplaceQu count: 6

 Unique values GarageType count: 7

 Unique values GarageYrBlt count: 98

 Unique values GarageFinish count: 4

 Unique values GarageCars count: 5

 Unique values GarageArea count: 441

 Unique values GarageQual count: 6

 Unique values GarageCond count: 6

 Unique values PavedDrive count: 3

 Unique values WoodDeckSF count: 274

 Unique values OpenPorchSF count: 202

 Unique values EnclosedPorch count: 120

 Unique values 3SsnPorch count: 20

 Unique values ScreenPorch count: 76

 Unique values PoolArea count: 8

 Unique values PoolQC count: 4

 Unique values Fence count: 5

 Unique values MiscFeature count: 5

 Unique values MiscVal count: 21

 Unique values MoSold count: 12

 Unique values YrSold count: 5

 Unique values SaleType count: 9

 Unique values SaleCondition count: 6

 Unique values SalePrice count: 663

## Bin MSSubClass

In [82]:
# Look at MSSubClass value counts for binning
hp_train_df['MSSubClass'].value_counts()

20     536
60     299
50     144
120     87
30      69
160     63
70      60
80      58
90      52
190     30
85      20
75      16
45      12
180     10
40       4
Name: MSSubClass, dtype: int64

In [83]:
# Choose a cutoff value and create a list of MSSubClass to be replaced
# use the variable name `MSSubClass_to_replace`
cutoff_value = 90

# Get the counts of each MSSubClass
MSSubClass_counts = hp_train_df['MSSubClass'].value_counts()

# Identify MSSubClass values to be replaced
MSSubClass_to_replace = list(MSSubClass_counts[MSSubClass_counts < cutoff_value].index)

# Replace in the DataFrame
for subclass in MSSubClass_to_replace:
    hp_train_df['MSSubClass'] = hp_train_df['MSSubClass'].replace(subclass, 'Other')

# Check to make sure binning was successful
print(hp_train_df['MSSubClass'].value_counts())

20       536
Other    481
60       299
50       144
Name: MSSubClass, dtype: int64

 ## Bin LotFrontage

In [85]:
# Look at LotFrontage  value counts for binning
hp_train_df['LotFrontage'].value_counts()

60     152
80     112
70      94
65      82
73      78
      ...
137      1
141      1
38       1
140      1
46       1
Name: LotFrontage, Length: 110, dtype: int64

In [86]:
# Choose a cutoff value and create a list of LotFrontage values to be replaced
# use the variable name `LotFrontage_to_replace`
cutoff_value = 60

# Get the counts of each LotFrontage value
LotFrontage_counts = hp_train_df['LotFrontage'].value_counts()

# Identify LotFrontage values to be replaced
LotFrontage_to_replace = list(LotFrontage_counts[LotFrontage_counts < cutoff_value].index)

# Replace in the DataFrame
for frontage_value in LotFrontage_to_replace:
    hp_train_df['LotFrontage'] = hp_train_df['LotFrontage'].replace(frontage_value, 'Other')

# Check to make sure binning was successful
print(hp_train_df['LotFrontage'].value_counts())

Other    942
60       152
80       112
70        94
65        82
73        78
Name: LotFrontage, dtype: int64

## Bin LotFrontage

In [87]:
# Look at LotArea value counts for binning
hp_train_df['LotArea'].value_counts()

7200     25
9600     24
6000     17
9000     14
8400     14
         ..
14601     1
13682     1
4058      1
17104     1
9717      1
Name: LotArea, Length: 1073, dtype: int64

In [88]:
# Choose a cutoff value for LotArea
cutoff_value_area = 20  

# Get the counts of each LotArea value
LotArea_counts = hp_train_df['LotArea'].value_counts()

# Identify LotArea values to be replaced
LotArea_to_replace = list(LotArea_counts[LotArea_counts < cutoff_value_area].index)

# Replace in the DataFrame
for area_value in LotArea_to_replace:
    hp_train_df['LotArea'] = hp_train_df['LotArea'].replace(area_value, 'Other')

# Check to make sure binning was successful
print(hp_train_df['LotArea'].value_counts())

Other    1411
7200       25
9600       24
Name: LotArea, dtype: int64

In [ ]:
## Bin 


## MZoning 5  Street  2     Alley 2     LotShape 4   LandContuer 4   Utilitlies 2  LotConfig 5 LandSlope 3  Bldg 5  MasVNR 4
## ExteriorQuality 4  ExtrCond  5   
## BasementQuality 4  BasementCondition 4 Basement Exoosure 4  BasementFullBath 4   BasementHalfbath  3  Fullbath 4   Half bath 3 

## CentralAr  2 
## HeatingQC  5

## KitchenAboveGround 4   Kitchen Qualtiy 4
## Fireplace 4   FirePlaceQC  5

## GarageCar 5  Grarage Finish 3   Garage Quality 5 GarageCond 5   PavedDrive 3 
## PoolQC 3 Fence 4
## MiscFeatures 4
## YearSold 5

In [93]:
# # Look at LotShape value counts for binning
hp_train_df['Neighborhood'].value_counts()

NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64

## Data Preprocessing for Test Data

In [16]:
# Display basic information about the testing dataset
print("Training Dataset Info:")
print(hp_test_df.info())

Training Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     1443 non-null   object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB
None

In [17]:
# Display columns with missing values and their counts
missing_values = hp_test_df.isnull().sum()
missing_columns = missing_values[missing_values > 0]
print("Columns with Missing Values:")
print(missing_columns)

Columns with Missing Values:
MSZoning           4
LotFrontage      227
Alley           1352
Utilities          2
Exterior1st        1
Exterior2nd        1
MasVnrType        16
MasVnrArea        15
BsmtQual          44
BsmtCond          45
BsmtExposure      44
BsmtFinType1      42
BsmtFinSF1         1
BsmtFinType2      42
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
BsmtFullBath       2
BsmtHalfBath       2
KitchenQual        1
Functional         2
FireplaceQu      730
GarageType        76
GarageYrBlt       78
GarageFinish      78
GarageCars         1
GarageArea         1
GarageQual        78
GarageCond        78
PoolQC          1456
Fence           1169
MiscFeature     1408
SaleType           1
dtype: int64

## Handle Null Values for hp_test_df

In [18]:
# Handle missing values
# Dropping columns with a high percentage of missing values  >1000
## Only 'FireplaceQu' have 690
columns = ['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature']
hp_test_df.drop(columns=columns, inplace=True)

In [19]:
# Reveiw the columns after dropping 5 columns wiht high percentages of missing value
missing_values = hp_test_df.isnull().sum()
missing_columns = missing_values[missing_values > 0]
print("Columns with Missing Values:")
print(missing_columns)

Columns with Missing Values:
MSZoning          4
LotFrontage     227
Utilities         2
Exterior1st       1
Exterior2nd       1
MasVnrType       16
MasVnrArea       15
BsmtQual         44
BsmtCond         45
BsmtExposure     44
BsmtFinType1     42
BsmtFinSF1        1
BsmtFinType2     42
BsmtFinSF2        1
BsmtUnfSF         1
TotalBsmtSF       1
BsmtFullBath      2
BsmtHalfBath      2
KitchenQual       1
Functional        2
GarageType       76
GarageYrBlt      78
GarageFinish     78
GarageCars        1
GarageArea        1
GarageQual       78
GarageCond       78
SaleType          1
dtype: int64

## Impute Missing Values hp_test_df

In [20]:
# Impute missing values in numerical columns with the mean
hp_test_df.fillna(hp_test_df.mean(), inplace=True)

# Impute missing values in categorical columns with the mode
hp_test_df.fillna(hp_test_df.mode().iloc[0], inplace=True)

C:\Users\Owner\AppData\Local\Temp\ipykernel_54320\1420030105.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  hp_test_df.fillna(hp_test_df.mean(), inplace=True)

In [21]:
# Convert 'LotFrontage' to int
hp_test_df['LotFrontage'] = hp_test_df['LotFrontage'].astype(int)

## Review hp_test_df for missing values

In [22]:
# Reveiw the columns after:
# dropping columns wiht high percentages of missing value
# Fill null values with imputation strategy

missing_values = hp_test_df.isnull().sum()
missing_columns = missing_values[missing_values > 0]
print("Columns with Missing Values:")
print(missing_columns)

Columns with Missing Values:
Series([], dtype: int64)

## Check duplicates for hp_test_df

In [23]:
# Check the number of unique values in each column
hp_test_df.nunique()

Id               1459
MSSubClass         16
MSZoning            5
LotFrontage       115
LotArea          1106
                 ...
MiscVal            26
MoSold             12
YrSold              5
SaleType            9
SaleCondition       6
Length: 75, dtype: int64

In [24]:
# Check for duplicated values in the 'Id' column
subset_columns = ['Id']
duplicate_rows_subset = hp_test_df[hp_test_df.duplicated(subset=subset_columns)]
if duplicate_rows_subset.empty:
    print("No duplicate rows based on 'Id' column.")
else:
    print("Duplicate rows based on 'Id' column:")
    print(duplicate_rows_subset)

No duplicate rows based on 'Id' column.

## Convert necessary columns to appropriate data types

In [25]:
# Convert necessary columns to appropriate data types
hp_test_df['MSSubClass'] = hp_test_df['MSSubClass'].astype('category')
hp_test_df['MSZoning'] = hp_test_df['MSZoning'].astype('category')
hp_test_df['Street'] = hp_test_df['Street'].astype('category')
hp_test_df['LotShape'] = hp_test_df['LotShape'].astype('category')
hp_test_df['LandContour'] = hp_test_df['LandContour'].astype('category')

# Review the train & test cleaned dataframes

In [26]:
# Display the resulting DataFrame
hp_train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [27]:
# Display the resulting DataFrame
hp_test_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80,11622,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,120,0,0,6,2010,WD,Normal
1,1462,20,RL,81,14267,Pave,IR1,Lvl,AllPub,Corner,...,36,0,0,0,0,12500,6,2010,WD,Normal
2,1463,60,RL,74,13830,Pave,IR1,Lvl,AllPub,Inside,...,34,0,0,0,0,0,3,2010,WD,Normal
3,1464,60,RL,78,9978,Pave,IR1,Lvl,AllPub,Inside,...,36,0,0,0,0,0,6,2010,WD,Normal
4,1465,120,RL,43,5005,Pave,IR1,HLS,AllPub,Inside,...,82,0,0,144,0,0,1,2010,WD,Normal

# Export the cleaned data to CSV

In [28]:
hp_train_df.to_json('../Preprocessed_Data/preprocessed_hp_train.json', orient='records', lines=True)
hp_train_df.to_csv('../Preprocessed_Data/preprocessed_hp_train.csv', index=False)

In [29]:
hp_test_df.to_json('../Preprocessed_Data/preprocessed_hp_test.json', orient='records', lines=True)
hp_test_df.to_csv('../Preprocessed_Data/preprocessed_hp_test.csv', index=False)